### ISSUE TITLE
Pin version

### ISSUE THREAD

**Issue by shyun3** [zapling/mason-conform.nvim#10]
Is there a way to specify only a specific version of a formatter to install, kind of like what's available in [mason-tool-installer.nvim](https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim)?

**Comment by zapling** [comment]
No there isn't. I'm not familiar with `mason-tool-installer.nvim`, I personally use https://github.com/zapling/mason-lock.nvim to get more control over all my mason packages.
