### ISSUE TITLE
Allow configuring which formatters are installed with mason

### ISSUE THREAD

**Issue by agirardeau** [zapling/mason-conform.nvim#2]
Sometimes it's preferable to install a formatter manually rather than through mason. For example, `rustfmt` prints an error message in mason:

```
deprecated: rustfmt should now be installed via rustup.
```

**Comment by zapling** [comment]
Since mason has added the `deprecated` flag to the `rustfmt` package I think we can safely remove it from the conform to mason mapping, and this plugin will stop trying to install it.
