### ISSUE TITLE
`clang-format` mapping?

### ISSUE THREAD

**Issue by shyun3** [zapling/mason-conform.nvim#6]
In `conform`, I have my `c` formatter specified as:
```lua
formatters_by_ft = {
  c = { "clang-format" },
},
```
But this plugin didn't auto-install `clang-format`. Then I noticed in the [mapping](https://github.com/zapling/mason-conform.nvim/blob/ddb854253dd293c673f77c5fc480f849258c3d73/lua/mason-conform/mapping.lua#L26) that it is expecting `clang_format` as the name instead.

Was there a specific reason this was done? Could a mapping for `clang-format` be added? This works fine for `conform` and is also the actual name of the executable.

**Comment by zapling** [comment]
I think this is just a mistake on my part, I have pushed https://github.com/zapling/mason-conform.nvim/commit/40133b4bf3e0322e7983f20183a062ba4a6db122  that changes the name to `clang-format`. Thanks for the ticket!
