### ISSUE TITLE
mason-conform prevents system installed formatters from functioning

### ISSUE THREAD

**Issue by miversen33** [zapling/mason-conform.nvim#9]
I am not really sure how this can be addressed (I noticed a similar issue with #2 ) but in my case, I have `isort` installed on my system (found at `$HOME/.local/bin/isort`) and `ruff` installed with mason (found at `$HOME/.local/share/mason/packages/ruff/venv/bin/ruff`).

I would expect _both_ paths to work, not one or the other. I assumed mason-conform _added_ the mason binaries to path but I may be mistaken?

I can of course fix this by simply moving `isort` into mason but I am not super fond of the idea that I cannot use system installed formatters.

**Comment by zapling** [comment]
> I would expect both paths to work, not one or the other. I assumed mason-conform added the mason binaries to path but I may  be mistaken?

This plugin only detects the formatters that is registered with conform, and downloads them (via mason).

> I can of course fix this by simply moving isort into mason but I am not super fond of the idea that I cannot use system installed formatters.

Sounds like you need to add both directories to your shells `PATH`.
